#!/bin/bash

if [ -z "$1" ]; then
  echo "Please provide a project name."
  exit 1
fi
PROJECT_NAME=$1

#
# ---------- GENERATE HIERARCHY ---------- #
mkdir -p "${PROJECT_NAME}/src/main/java/my/pkg"
mkdir -p "${PROJECT_NAME}/src/test/java/my/pkg"
mkdir -p "${PROJECT_NAME}/gradle/wrapper"
cd "${PROJECT_NAME}" || exit

#
# ---------- OVERVIEW.HTML ---------- #
cat <<EOL >src/overview.html
<html><body>
<p> ${PROJECT_NAME} </p>
</body></html>
EOL

#
# ---------- GRADLE-WRAPPER.PROPERTIES ---------- #
cat <<EOL >gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOL

#
# ---------- GRADLE-WRAPPER.JAR ---------- #
cp /Users/manuelfarzini/Personal/dev/utils/gradle-wrapper.jar gradle/wrapper/

#
# ---------- BUILD.GRADLE ---------- #
cat <<EOL >build.gradle
plugins {
  id 'java'
  id 'jacoco'
  id 'com.diffplug.spotless' version '6.22.0'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

repositories {
  mavenCentral()
}

dependencies {
  testImplementation('org.junit.jupiter:junit-jupiter:5.9.2')
  testRuntimeOnly('org.junit.platform:junit-platform-launcher')
  testImplementation('org.hamcrest:hamcrest:2.2')
}

test {
  useJUnitPlatform()
  testLogging {
    events 'passed', 'skipped', 'failed'
  }
  finalizedBy jacocoTestReport
  defaultCharacterEncoding = 'UTF-8'
}

tasks.withType(JavaExec) {
  enableAssertions = project.hasProperty('enableAssertions') ? project.getProperty('enableAssertions') : false
}

task runClass(type: JavaExec) {
  dependsOn build
  group = 'Execution'
  description = 'Runs the main method of a class given its fully qualified name.'
  mainClass = project.hasProperty('mainClass') ? project.getProperty('mainClass') : 'my.pkg.${PROJECT_NAME}'
  classpath = sourceSets.main.runtimeClasspath
  defaultCharacterEncoding = 'UTF-8'
}

javadoc {
  options {
    encoding = 'UTF-8'
    charSet = 'UTF-8'
    links = [ 'https://docs.oracle.com/en/java/javase/17/docs/api/' ]
    docTitle = 'Build Automation Tool ${PROJECT_NAME}'
    overview = 'src/overview.html'
    header = '<script type=\'text/javascript\' src=\'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\'></script>'
    showFromPrivate()
    addStringOption 'Xdoclint:none', '-quiet'
    addBooleanOption '-allow-script-in-comments', true
  }
}

spotless {
  enforceCheck false
  java {
    googleJavaFormat('1.17.0')
    removeUnusedImports()
    endWithNewline()
  }
}
EOL

#
# ---------- GRADLEW ---------- #
cat <<'EOL' >gradlew
#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
EOL

#
# ---------- GRADLEW.BAT ---------- #
cat <<'EOL' >gradlew.bat
@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar


@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
EOL

#
# ---------- PROJ.JAVA IN MAIN DIRECTORY ---------- #
cat <<EOL >src/main/java/my/pkg/${PROJECT_NAME}.java
package my.pkg;

import java.util.Objects;

/**
 * A ${PROJECT_NAME}.
 *
 * <p>
 * A typical ${PROJECT_NAME} is characterized by the following.
 * <ul>
 * <li>A <em>some</em> …
 * <li>An <em>thing</em> …
 * </ul>
 *
 * <p>${PROJECT_NAME} is able to do the following:
 * <ul>
 * <li>It can …
 * <li>It can …
 * </ul>
 *
 * <p>Equality and ordering are based …
 */
public class ${PROJECT_NAME} implements Comparable<${PROJECT_NAME}> {

    /** . */
    private final String state;

    /**
     * Returns a string representation of this.
     *
     * @return a string representation of this.
     */
    @Override
    public String toString() {
        // XXX: to implement
        return "state: " + state;
    }
    /*-
     * AF(state)
     *  =
     */

    // Implements the RI predicate and it's used for assertions.
    private boolean repOk() {
        // XXX: to implement
        boolean ok = !(Objects.requireNonNull(state).isBlank());
        // ok && …
        // …
        return ok;
    }
    /*-
     * RI(state)
     *  =
     */

    /**
     * Builds a ${PROJECT_NAME} object.
     *
     * @param data the value to store in the object.
     * @throws …
     */
    public ${PROJECT_NAME}(final String data) {
        this.state = data;
    }

    /**
     * Returns the state of this.
     *
     * @return the state of this.
     */
    public String getState() {
        return state;
    }

    /**
     * Compare this with the given other ${PROJECT_NAME}.
     *
     * <p>The comparison is based on …
     *
     * <p>Returns {@code true} if the argument o is not {@code null}, o is an ${PROJECT_NAME} and
     * the state of this is the same as the state of o. Returns {@code false} false otherwise.
     *
     * @param o the object to compare with.
     * @return {@code true} if this is the same as the o argument, {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        // XXX: to implement
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ${PROJECT_NAME} other = (${PROJECT_NAME}) o;
        return state.equals(other.state);
    }

    /**
     * Compare this with the given other {@code ${PROJECT_NAME}}.
     *
     * Returns a negative integer, zero, or a positive integer as this object is less than, equal
     * to, or greater than the given {@code ${PROJECT_NAME}}.
     *
     * <p>The comparison is based on …
     *
     * @param o the {@code ${PROJECT_NAME}} to compare with.
     * @return a negative integer, zero, or a positive integer as this object is less than, equal,
     *         or greater than the given {@code ${PROJECT_NAME}}.
     */
    @Override
    public int compareTo(${PROJECT_NAME} o) {
        // XXX: to implement
        return state.compareTo(o.state);
    }

    /**
     * Returns the hash code for this.
     *
     * <p>The hash code is based on …
     *
     * @return the hash code for this.
     */
    @Override
    public int hashCode() {
        // XXX: to implement
        return Objects.hash(state);
    }

    // Fast test.
    public static void main(String[] args) {
        ${PROJECT_NAME} test = new ${PROJECT_NAME}("test");
        System.out.println(test);
    }
}
EOL

#
# ---------- MAIN.JAVA IN MAIN DIRECTORY ---------- #
cat <<EOL >src/main/java/my/pkg/${PROJECT_NAME}Client.java
package my.pkg;

import java.util.Scanner;

  /** 
   * A {@code ${PROJECT_NAME}Client} allows verification of the behaviour of a ${PROJECT_NAME}
   * 
   * <p>…
   * 
   * <p>For more details, see the <em>overview</em> of this package.
   */
public class ${PROJECT_NAME}Client {

    /**
     * Simulates a {@code {$PROJECT_NAME}}
     *
     * <p>Read … the firs argument … the second argument …
     *
     * @param args the command line arguments.
     * @throws …
     */
    public static void main(String[] args) {
          System.out.println("Hello from ${PROJECT_NAME}Client");
  }
}
EOL

#
# ---------- PACKAGE-INFO.JAVA IN MAIN DIRECTORY ---------- #
cat <<'EOL' >src/main/java/my/pkg/package-info.java
/** . */
package my.pkg;
EOL

#
# ---------- PROJTEST.JAVA IN TEST DIRECTORY ---------- #
cat <<EOL >src/test/java/my/pkg/${PROJECT_NAME}Test.java
package my.pkg;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class ${PROJECT_NAME}Test {

    @Test
    public void remembersTen() {
        ${PROJECT_NAME} ten_test = new ${PROJECT_NAME}("10");
        assertEquals(ten_test.(), "state: 10");
    }

    @Test
    public void remembersTwelve() {
        ${PROJECT_NAME} twelve_test = new ${PROJECT_NAME}("12");
        assertEquals(twelve_test.printDesc(), "state: 12");
    }
}
EOL

sudo chmod +x gradlew
./gradlew runClass -x test -PmainClass=my.pkg.${PROJECT_NAME}Client
