[mgr]
ratio = [2, 5, 5]
sort_dir_first = true
sort_by = "extension"
show_simlink = true
show_hidden = false
linemode = "mtime"
scrolloff = 10

[preview]
wrap = "yes"
tab_size = 2
max_width = 1000
max_height = 1000
image_delay = 30
image_quality = 50

[opener]
edit = [
    { run = 'nvim %s', desc = "nvim", block = true, for = "unix" },
]

open = [
    { run = 'open %s', desc = "open", for = "macos" },
]

reveal = [
    { run = 'xdg-open %d1', desc = "reveal", for = "linux" },
    { run = 'open -R %s1', desc = "reveal", for = "macos" },
    { run = '''exiftool %s1; echo "Press enter to exit"; read _''', block = true, desc = "show EXIF", for = "unix" },
]

term = [
    { run = 'open -na Ghostty --args -e zsh -c "cd %s1; exec zsh"', desc = "term", for = "macos" },
]

[open]
prepend_rules = [
    { url = "*.pdf", use = ["open", "reveal"] },
    { url = "*.md", use = ["edit", "open", "reveal"] },
    { url = "*/", use = ["term", "edit", "open"] },
]
