[mgr]
ratio = [2, 5, 5]
sort_dir_first = true
sort_by = "extension"
show_simlink = true
show_hidden = true
linemode = "mtime"
scrolloff = 10

[preview]
wrap = "yes"
tab_size = 2
max_width = 1000
max_height = 1000
image_delay = 30
image_quality = 50


[opener]
edit = [
	# { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
	{ run = 'open "$@"', desc = "open", for = "macos" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "reveal", for = "linux" },
	{ run = 'open -R "$1"', desc = "reveal", for = "macos" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "show EXIF", for = "unix" },
]
# extract = [
# 	{ run = 'ya pub extract --list "$@"', desc = "extract here", for = "unix" },
# ]
term = [
    { run = 'open -na Ghostty --args -e zsh -c "cd "$@"; exec zsh"', desc = "term", for = "macos" },
]

[open]
prepend_rules = [
    { url = "*.pdf", use = ["open", "reveal"] },
    { url = "*.md", use = ["edit", "open", "reveal"] },
    { url = "*/", use = ["term", "edit", "open" ] },
]
